### ISSUE TITLE
Confused about endpoint config

### ISSUE THREAD

**Issue by adz** [boydm/phoenix_integration#16]
I really like this library -- it's so much nicer with `|>`. I have just got started with phoenix, so excuse me while still learning basics!

So my confusion: in setup, Step 3 you say: 

    Alternately you could place the call to use PhoenixIntegration in your conn_case.ex file. 
    Just make sure it is after the definition of @endpoint.

Ignoring the `use PhoenixIntegration` point, given that there _is_ an @endpoint definition in conn_case.ex, why is it necessary to do it again under config/test.exs for :phonix_integration (as stated in "Step 1"?)

I tried without that config, and everything seems to work ok...

**Comment by boydm** [comment]
Well... I don't remember.

That could likely be for an older version of Phoenix. I have a few catch things to do to fully test it out under Phoenix 1.3 before I release version 0.4 of the library.

I'd bet it was required under Phoenix 1.2 and might be unnecesary now... Thank you for pointing it out! If that indeed turns out to be the case, I'll modify the docs.

**Comment by adz** [comment]
Ok, so after playing some more I've found it *is* necessary when using the functions that initiate a web request... which is of course why you need it -- you're calling "get" and friends within the PhoenixIntegration module...

It's not necessary when calling the "assert_response".
